# Generated by Django 3.1.7 on 2021-04-29 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('emailCliente', models.EmailField(max_length=200)),
                ('numeroTelefono', models.CharField(max_length=10)),
                ('direccionCliente', models.CharField(max_length=500)),
                ('gpsCliente', models.CharField(max_length=300)),
                ('statusCliente', models.CharField(choices=[('Activo', 'Activo'), ('Denegado', 'Denegado'), ('Baja', 'Baja')], default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='colonia',
            fields=[
                ('idColonia', models.AutoField(primary_key=True, serialize=False)),
                ('nombreColonia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEstado', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='gastoEquipo',
            fields=[
                ('idEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('statusEquipo', models.CharField(choices=[('Pagado', 'Pagado'), ('Adeudo', 'Adeudo')], default='Adeudo', max_length=50)),
                ('numeroPagos', models.PositiveIntegerField()),
                ('montoPago', models.PositiveIntegerField()),
                ('concepto', models.CharField(max_length=300)),
                ('nombreProveedor', models.CharField(max_length=100)),
                ('motivoCompra', models.CharField(max_length=200)),
                ('nombreResponsable', models.CharField(max_length=100)),
                ('numeroFactura', models.CharField(max_length=20)),
                ('comentarios', models.TextField(default='Sin comentarios')),
            ],
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreServicio', models.CharField(max_length=200)),
                ('descripcionServicio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tarjeta',
            fields=[
                ('idTarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTarjeta', models.CharField(max_length=100)),
                ('numeroTarjeta', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='tecnico',
            fields=[
                ('idTecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTecnico', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reporte',
            fields=[
                ('idReporte', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReporte', models.DateField()),
                ('descripcionReporte', models.TextField()),
                ('solucionReporte', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=50)),
                ('descripcionSolucion', models.TextField()),
                ('costoReporte', models.PositiveIntegerField()),
                ('tipoPago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], max_length=50)),
                ('observacionesReporte', models.TextField(default='Sin observaciones')),
                ('idClienteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.cliente')),
                ('idTecnicoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='repetidor',
            fields=[
                ('idRepetidor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nombreRepetidor', models.CharField(max_length=300)),
                ('nombreResponsable', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=10)),
                ('direccionRepetidor', models.CharField(max_length=500)),
                ('gpsRepetidor', models.CharField(max_length=100)),
                ('señas', models.CharField(max_length=500)),
                ('paqueteInternet', models.CharField(max_length=100)),
                ('ventaMensual', models.PositiveIntegerField()),
                ('idColoniaFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.colonia')),
            ],
        ),
        migrations.CreateModel(
            name='otrosIngresos',
            fields=[
                ('idIngresos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('statusIngreso', models.CharField(choices=[('Pagado', 'Pagado'), ('Adeudo', 'Adeudo')], default='Adeudo', max_length=50)),
                ('montoPago', models.PositiveIntegerField()),
                ('concepto', models.CharField(max_length=300)),
                ('numeroNota', models.CharField(max_length=20)),
                ('idClienteFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('idMunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMunicipio', models.CharField(max_length=150)),
                ('idEstadoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.estado')),
            ],
        ),
        migrations.CreateModel(
            name='detalleServicio',
            fields=[
                ('idDetalleServicio', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDetalle', models.DateField()),
                ('costoInstalacion', models.PositiveIntegerField()),
                ('pagoMensual', models.PositiveIntegerField()),
                ('tipoPago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], max_length=50)),
                ('idClienteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.cliente')),
                ('idServicioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
                ('idTecnicoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tecnico')),
            ],
        ),
        migrations.AddField(
            model_name='colonia',
            name='idMunicipioFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.municipio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idColoniaFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.colonia'),
        ),
    ]
