# Generated by Django 3.1.7 on 2021-04-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='solucionReporte',
            field=models.TextField(default='Sin solucion'),
        ),
    ]
