# Generated by Django 3.1.7 on 2021-04-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20210429_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='descripcionSolucion',
        ),
    ]
