# Generated by Django 3.1.7 on 2021-05-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20210429_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='numeroTelefono',
            new_name='numeroTelefonoUno',
        ),
        migrations.AddField(
            model_name='cliente',
            name='numeroTelefonoDos',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
