# Generated by Django 3.1.7 on 2021-05-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20210508_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repetidor',
            old_name='telefono',
            new_name='numeroTelefonoUno',
        ),
        migrations.AddField(
            model_name='repetidor',
            name='numeroTelefonoDos',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
