# Generated by Django 3.1.7 on 2021-05-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20210508_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=20)),
                ('nombrePago', models.CharField(max_length=300)),
                ('fehcaPago', models.DateField()),
                ('montoPago', models.PositiveIntegerField()),
                ('tipoPago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Deposito', 'Deposito'), ('Transferencia', 'Transferencia'), ('Tienda', 'Tienda')], max_length=50)),
                ('comentarios', models.TextField(default='Sin comentarios')),
            ],
        ),
    ]
