# Generated by Django 3.1.7 on 2021-05-22 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_pagos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='fehcaPago',
            new_name='fechaPago',
        ),
    ]
